// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig, env } from "prisma/config";
import path from 'node:path';
import dotenv from 'dotenv';

// Load .env from the project root explicitly
//loadEnv({ path: ".env" });
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL")    
  },
});
